#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

# Build docker image
git clone https://github.com/webcracy/dokku-pg-dockerfiles /tmp/dokku-pg-dockerfiles
docker build -q=true -t kloadut/postgresql /tmp/dokku-pg-dockerfiles
rm -rf /tmp/dokku-pg-dockerfiles
