#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"

PG_APP_IMAGE="postgresql/$APP"
PG_VOLUME_PATH="$DOKKU_ROOT/.postgresql/volume_$APP"

# Check if an existing DB volume exists
PG_APP_IMAGE_ID=$(docker images | grep "$PG_APP_IMAGE" |  awk '{print $3}')
if [[ -n $PG_APP_IMAGE_ID ]] && [[ -f $PG_VOLUME_PATH ]]; then
    echo    "-----> Checking status of PostgreSQL"

    # Check if DB container is installed
    PG_IMAGE=$(docker images | grep "kloadut/postgresql " |  awk '{print $3}')
    if [[ -z $PG_IMAGE ]]; then
        echo "PostgreSQL image not found... Did you run 'dokku plugins-install' ?"
        exit 1
    fi

    echo    "       Found image postgresql/$APP database"
    echo -n "       Checking status... "

    PG_APP_CONTAINER_ID=$(docker ps | grep "$PG_APP_IMAGE" |  awk '{print $1}')
    if [[ -n $PG_APP_CONTAINER_ID ]]; then
        echo "ok."
    else
        echo "stopped."

        PG_VOLUME="`cat $PG_VOLUME_PATH`:/opt/postgresql"

        echo -n "       Launching $PG_APP_IMAGE... "
        echo "COMMAND: docker run -v $PG_VOLUME -p 5432 -d $PG_APP_IMAGE /usr/bin/start_pgsql.sh $DB_PASSWORD"
        ID=$(docker run -v $PG_VOLUME -p 5432 -d $PG_APP_IMAGE /usr/bin/start_pgsql.sh $DB_PASSWORD)
        echo "COMMAND: dokku postgresql:link $APP $APP"
        dokku postgresql:link $APP $APP
        sleep 1
        echo "ok."
    fi
fi
